# Generated by Django 2.2.6 on 2019-12-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('short_desc', models.CharField(help_text='A quick short description of the Artwork', max_length=100)),
                ('desc', models.CharField(help_text='A longer more indepth description of the ArtWork', max_length=5000)),
                ('slug', models.CharField(blank=True, editable=False, max_length=100)),
                ('tag', models.CharField(choices=[('photo', 'Photo'), ('charecter design', 'Charecter Design'), ('visual design', 'Visual Design'), ('cartoon', 'Cartoon'), ('fine art', 'Fine Art')], max_length=32)),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
