# Generated by Django 2.2.6 on 2019-12-18 20:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('artpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='image',
            field=models.ImageField(default=datetime.datetime(2019, 12, 18, 20, 8, 45, 214100, tzinfo=utc), upload_to='gallery'),
            preserve_default=False,
        ),
    ]
