# Generated by Django 2.2.6 on 2019-12-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artpages', '0002_artwork_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='tag',
            field=models.CharField(choices=[('photo', 'Photo'), ('charecter_design', 'Charecter Design'), ('visual_design', 'Visual Design'), ('cartoon', 'Cartoon'), ('fine_art', 'Fine Art')], max_length=32),
        ),
    ]
