# Generated by Django 2.2.6 on 2019-12-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artpages', '0003_auto_20191222_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=50000)),
                ('major', models.CharField(max_length=100)),
            ],
        ),
    ]
